### ISSUE TITLE
Quitar requisito de .ssh/config

### ISSUE THREAD

**Issue by imunizaga** [magnet-cl/magnetizer-fabric#6]
Ahora si el usuario no tiene el archivo .ssh/config, tira infinitos mensajes de error.

**Comment by jslopez** [comment]
Esto debería solucionarse con un .ssh/config por defecto, beneficiando así a toda la comunidad.

**Comment by imunizaga** [comment]
Ya que magnetizer define el "por defecto". Magnetizer podría hacer touch del archivo config.

**Comment by imunizaga** [comment]
Subí un template nuevo de ssh config, pero no cacho la forma óptima de pasárselo al usuario, ya que todo comando busca el archivo.

**Comment by jslopez** [comment]
En ese caso sería ideal en el install.sh

**Comment by imunizaga** [comment]
¿Lo haces tu? :D

**Comment by imunizaga** [comment]
Lo hice yo

**Comment by jslopez** [comment]
Lo arreglé yo, c73e9f7490c85f3a0dd930c5ca6abd576925bf4c
