### ISSUE TITLE
[error] when using postgresql.install

### ISSUE THREAD

**Issue by ateston** [magnet-cl/magnetizer-fabric#8]
Installing PostgreSQL and its development packages.
[localhost] sudo: DEBIAN_FRONTEND=noninteractive apt-get install --quiet --assume-yes postgresql-9.3
[localhost] out: sudo password:Leyendo lista de paquetes...
[localhost] out: Creando árbol de dependencias...
[localhost] out: Leyendo la información de estado...
[localhost] out: E: No se ha podido localizar el paquete postgresql-9.3
[localhost] out: E: No se pudo encontrar ningún paquete con la expresión regular «postgresql-9.3»
[localhost] out: 

Fatal error: sudo() received nonzero return code 100 while executing!

Requested: DEBIAN_FRONTEND=noninteractive apt-get install --quiet --assume-yes postgresql-9.3
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "DEBIAN_FRONTEND=noninteractive apt-get install --quiet --assume-yes postgresql-9.3"

Sorry for spanish C:, using Ubuntu 12.04.4

**Comment by jslopez** [comment]
It's because @cristiandonosoc modified the task setting 9.3 as the default version (which is the default for ubuntu 14.04), you should run the task giving the default version for ubuntu 12.04:

`fab postgresql.install:9.1`
